### ISSUE TITLE
Connection error with NSIDC_ECS products

### ISSUE THREAD

**Issue by aldotapia** [nsidc/earthdata#96]
I've got issues trying to download data from `NSIDC_ECS` data center, any hints/fix?

```
#!/usr/bin/env python
from earthdata import Auth, DataGranules, Store

auth = Auth().login(strategy="netrc") 
Query = DataGranules(auth).short_name('MOD10A2').bounding_box(-73.73,-55.01,-67.05,-17.63).downloadable(True)
granules = Query.get(5)
store = Store(auth)

store.get(granules, "/path/to/MOD10A2/")
```

Error message:

```
You're now authenticated with NASA Earthdata Login
Using token with expiration date: 08/16/2022
 Getting 5 granules, approx download size: 0.0 GB
SUBMITTING | : 100%|█████████████████████████████| 5/5 [00:00<00:00, 760.91it/s]
PROCESSING | :   0%|                                      | 0/5 [00:00<?, ?it/s]Error while downloading the file MOD10A2.A2000049.h11v10.061.2020041202751.hdf
Error while downloading the file MOD10A2.A2000049.h12v13.061.2020041203737.hdf
Error while downloading the file MOD10A2.A2000049.h14v14.061.2020041204245.hdf
Error while downloading the file MOD10A2.A2000049.h11v11.061.2020041202514.hdf
Error while downloading the file MOD10A2.A2000049.h12v12.061.2020041203240.hdf
Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/earthdata/store.py", line 222, in _download_file
    r = session.head(url)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 564, in head
    return self.request('HEAD', url, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/earthdata/store.py", line 222, in _download_file
    r = session.head(url)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 564, in head
    return self.request('HEAD', url, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/earthdata/store.py", line 222, in _download_file
    r = session.head(url)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 564, in head
    return self.request('HEAD', url, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
PROCESSING | :  20%|██████                        | 1/5 [00:00<00:02,  1.45it/s]
Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/earthdata/store.py", line 222, in _download_file
    r = session.head(url)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 564, in head
    return self.request('HEAD', url, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/earthdata/store.py", line 222, in _download_file
    r = session.head(url)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 564, in head
    return self.request('HEAD', url, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/aldotapia/opt/anaconda3/envs/ee/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

PROCESSING | : 100%|██████████████████████████████| 5/5 [00:00<00:00,  7.23it/s]
COLLECTING | : 100%|███████████████████████████| 5/5 [00:00<00:00, 97997.76it/s]
```

**Comment by aldotapia** [comment]
@betolink you are totally right. I was trying to download +18k files with 8 threads and I had many error messages (although I could download files). I changed to 1 thread and everything is working fine (4 threads also raised errors so I prefer go slow but safe)
